### ISSUE TITLE
WindowsError: [Error -2147417850] Cannot change thread mode after it is set

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#445]
Versions: Win10 x64 (build 1511), Python 2.7.14 (64-bit).

I'm getting pretty basic error on importing the latest branch (first time it worked on clean Python+dependencies; second+ runs are all failing). The code to reproduce (running from the repo root folder):
```python
from __future__ import print_function
import os, sys, time
script_dir = os.path.dirname(__file__)
sys.path.append(script_dir)
os.chdir(script_dir)
import pywinauto
print(pywinauto.__version__)
```

Traceback:
```python
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 326, in RunScript
    exec codeObject in __main__.__dict__
  File "C:\...\pywinauto_fork\test_notepad.py", line 6, in <module>
    import pywinauto
  File "C:\...\pywinauto_fork\pywinauto\__init__.py", line 52, in <module>
    from . import findwindows
  File "C:\...\pywinauto_fork\pywinauto\findwindows.py", line 39, in <module>
    from . import win32functions
  File "C:\...\pywinauto_fork\pywinauto\win32functions.py", line 35, in <module>
    from . import win32defines, win32structures
  File "C:\...\pywinauto_fork\pywinauto\win32structures.py", line 42, in <module>
    from . import sysinfo
  File "C:\...\pywinauto_fork\pywinauto\sysinfo.py", line 44, in <module>
    import comtypes  # noqa: E402
  File "C:\Python27\lib\site-packages\comtypes\__init__.py", line 165, in <module>
    CoInitializeEx()
  File "C:\Python27\lib\site-packages\comtypes\__init__.py", line 156, in CoInitializeEx
    _ole32.CoInitializeEx(None, flags)
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147417850] Cannot change thread mode after it is set
```

Looks like we must handle `RCP_E_CHANGED_MODE` error. Cite from MSDN thread:

> One important thing to note is that as this call to CoInitialize "failed" we don't want to call the "matching" CoUninitialize: we leave that up to the CoUninitialize that "matches" the original call to CoInitialize.

Need to test all these cases (I mean calling `CoInitialize` before pywinauto's import). Maybe some warning makes sense if we can't change thread mode.

**Comment by airelil** [comment]
Usually it means that another module already initialized STA mode so we can not switch to MTA, but I need to take a closer look into it.

**Comment by airelil** [comment]
I reproduced it also on my Win8. Seems as "Pythonwin - Python IDE and GUI Framework" makes earlier initialisation of COM threading mode. So in this case we'll try to fallback to the existing mode.

**Comment by vasily-v-ryabov** [comment]
Great, now can confirm it's not crashing. Thanks!
So 0.6.4 can go with this fix.

**Comment by andrewchenshx** [comment]
Versions: Win7 x64 , Python 3.7.3 (64-bit) , pywinauto-0.6.6
same error.

**Comment by airelil** [comment]
Try have a look at https://pywinauto.readthedocs.io/en/latest/HowTo.html#com-threading-model
Could be related

**Comment by andrewchenshx** [comment]
AttributeError: module 'sys' has no attribute 'coinit_flags'

**Comment by andrewchenshx** [comment]
@airelil , the 0.6.2.post1 version works.

**Comment by airelil** [comment]
If you are talking about pywinauto 0.6.2 it's probably the version before we switched the default model from STA to MTA.

Regarding the ```AttributeError```, are you trying to access it before assigning?
```
(py36) xxxxx@yyyyyyy:~$ ipython
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys                                                                                                                             

In [2]: print(sys.coinit_flags)                                                                                                                
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-933353e6a637> in <module>
----> 1 print(sys.coinit_flags)

AttributeError: module 'sys' has no attribute 'coinit_flags'

In [3]: sys.coinit_flags = 0                                                                                                                   

In [4]: print(sys.coinit_flags)                                                                                                                
0
```

**Comment by andrewchenshx** [comment]
1)OMG, so the attribute 'coinit_flags' is actually created by my code, and will be accessed by pywinauto?
2)regarding the default model, how about using the model already set by another imported module?

**Comment by airelil** [comment]
The flags are used by pythoncom. See http://www.icodeguru.com/WebServer/Python-Programming-on-Win32/appd.htm
I'm sorry if it was not clear from the explanation in the "how-to", but
Pywinauto mostly tries to adapt to the existing model, in case it is already set up by another module. It might still be buggy, but we need much more details before concluding it.

**Comment by ETreskovskis** [comment]
with pywinauto==0.6.8 I still had the same issue as it was described @vasily-v-ryabov 
currently the problem is solved according this example:
![image](https://user-images.githubusercontent.com/36953308/193564497-37a8280d-d503-474c-b8d3-4db8b39fb9a1.png)

**Comment by sgdva** [comment]
> with pywinauto==0.6.8 I still had the same issue as it was described [@vasily-v-ryabov](https://github.com/vasily-v-ryabov) currently the problem is solved according this example: ![image](https://user-images.githubusercontent.com/36953308/193564497-37a8280d-d503-474c-b8d3-4db8b39fb9a1.png)

Thank you! Since I can confirm this still happens on xlwings 0.33.6 and pywinauto 0.69 using python 3.13, declaring the first 2 imports solved it.
