### ISSUE TITLE
Cannot import pywinauto in python 3.7 64bit ( works on 32 bit)!!!

### ISSUE THREAD

**Issue by hieudepchai** [pywinauto/pywinauto#867]
## Problem
I want to use pywinauto for 64-bit game automation. I got stuck at calling the function  print_control_identifiers() when using python 32bit.
```
import pyautogui 
import psutil
import pywinauto
from pywinauto.application import Application
#global var
processid = 0
handle = pywinauto.findwindows.find_window(best_match='fifa')
app = pywinauto.application.Application().connect(handle=handle)
windows = app.windows()
fo4_window = app.window(title='FIFA ONLINE 4')
fo4_window.print_control_identifiers()
```
variables at break point before error:
![image](https://user-images.githubusercontent.com/38937534/71320926-4a3f6200-24e5-11ea-9451-6c7d6837cf77.png)

errror:
```
 
C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py:1091: UserWarning: 64-bit application should
be automated using 64-bit Python (you use 32-bit Python)
  UserWarning)
C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py:1010: UserWarning: Python process has no rights to make changes in the target GUI (run the script as Administrator)
  warnings.warn(warning_text, UserWarning)
Control Identifiers:
Traceback (most recent call last):
  File "c:\Users\Admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Offline Study\fo4_automation\run.py", line 15, in <module>
    fo4_window.print_control_identifiers()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 689, in print_control_identifiers
    print_identifiers([this_ctrl, ])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 660, in print_identifiers
    if hasattr(ctrl.element_info, 'automation_id'):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\win32_element_info.py", line 201, in automation_id
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\remote_memory_block.py", line 96, in __init__
    process_id)
pywinauto.remote_memory_block.AccessDenied: ('[WinError 5] Access is denied.process: %d', 1604)
```
When I switched to python 64-bit, I even couldn't import pywinauto ( already installed again with pip 64 bit)

```
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Offline Study\fo4_automation\run.py", line 7, in <module>
    import pywinauto
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1002, in <module>
    ( ['out', 'retval'], POINTER(POINTER(IUIAutomationElement)), 'element' )),
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
```
Hope to receive your answers

## Specifications

  - Pywinauto version:0.6.8
  - Python version and bitness: 3.7 64bit
  - Platform and OS: Windows 10

**Comment by vasily-v-ryabov** [comment]
First I need to say it's improper use of pywinauto. We don't recommend using low level functions like `find_elements` because you can't know all moments and assumptions that are handled by higher level objects. Read the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) about core concept.

The first error is most probably due to insufficient rights for Python process. `Application` object handles this and warns properly that you have to run Python script as Administrator especially when you're connecting to existing application process. Low level functions don't have such warnings and error messages.

The second error message is a `comtypes` issue which duplicates issue #868 . Let's track it there.

**Comment by vasily-v-ryabov** [comment]
Sorry, for this case it's almost proper use except you don't have to use `find_windows`, but you need `connect(title="...")`. Also you need 64-bit Python for 64-bit process if you're using default `Application(backend="win32")`. Using `backend="uia"` doesn't require 64-bit Python, but the hierarchy will be completely different and more detailed for some apps.

Just try earlier version of 64-bit Python or try `Application(backend="uia")` as a conclusion.

P.S. We may need to add more proper error message for this case.

**Comment by Ravi9562** [comment]
Hi. Whenever I import pywinauto I am getting below error
"
Traceback (most recent call last):
  File "D:\Python\Python38\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tejaw/PycharmProjects/anurag/Sample.py", line 3, in <module>
    import pywinauto
  File "D:\Python\Python38\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "D:\Python\Python38\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "D:\Python\Python38\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "D:\Python\Python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "D:\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "D:\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "D:\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "D:\Python\Python38\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "D:\Python\Python38\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "D:\Python\Python38\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "D:\Python\Python38\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "D:\Python\Python38\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1931, in <module>
    IUIAutomation._methods_ = [
  File "D:\Python\Python38\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "D:\Python\Python38\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "D:\Python\Python38\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
"

Please do help me in this.

**Comment by airelil** [comment]
I think it's still rebounds from https://github.com/pywinauto/pywinauto/issues/868. You might need to update your python to 3.8.2 or newer.

**Comment by Ravi9562** [comment]
> I think it's still rebounds from #868. You might need to update your python to 3.8.2 or newer.

Hi. I even tried with newer version but no change in output. Is there any patch kind of thing available for this.

**Comment by vasily-v-ryabov** [comment]
@Ravi9562 I think you need clean re-install of Python 3.8.2. Also please remove all *.pyc files. It is fixed in Python code, not in pywinauto.

**Comment by vasily-v-ryabov** [comment]
To make sure you're using correct Python:
```python
import sys
print(sys.executable)
```

**Comment by sshivanshu992** [comment]
D:\Python\Voice_Assistance\venv\Scripts\python.exe D:/Python/Voice_Assistance/guru.py
Traceback (most recent call last):
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\CWANSHU\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    from comtypes.gen import SpeechLib  # comtypes
ImportError: cannot import name 'SpeechLib' from 'comtypes.gen' (D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\gen\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CWANSHU\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>, <class 'ctypes.wintypes.LP_c_long'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Python/Voice_Assistance/guru.py", line 3, in <module>
    engine = pyttsx3.init('sapi5')
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\CWANSHU\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\pyttsx3\drivers\sapi5.py", line 6, in <module>
    engine = comtypes.client.CreateObject("SAPI.SpVoice")
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\gen\_C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4.py", line 56, in <module>
    ISpeechBaseStream._methods_ = [
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "D:\Python\Voice_Assistance\venv\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\CWANSHU\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

Process finished with exit code 1

**Comment by vasily-v-ryabov** [comment]
@sshivanshu992 please do clean installation of Python 3.8.2. It's a bug in Python core fixed in 3.8.2.

**Comment by eavictor** [comment]
For other people who have dependencies in their project blocking upgrade to python 3.8.2 or later.

Python 3.7.8 64bit (Windows 10 20H1) also works.

**Comment by TechnicalIllusion** [comment]
After updating to Python 3.8.4 I am still getting this issue. Fresh install of Windows and Python to no avail.
